using System;
using System.Collections.Generic;
using System.Text;

namespace ItemFix
{
    /// <summary>
    /// An ID that represents <see cref="User"/> | <seealso cref="Post"/>
    /// <para>Not generated by an end user</para>
    /// </summary>
    public struct ItemID
    {
        internal ItemID(string id, Type type)
        {
            this.ID = id;
            this.IDType = type;
        }

        /// <summary>
        /// Defines the type of ID this represents
        /// </summary>
        public enum Type
        {
            /// <summary>
            /// A simple <see cref="ItemFix.Post"/>
            /// </summary>
            Post,
            /// <summary>
            /// A simple <see cref="ItemFix.User"/>
            /// </summary>
            User, 
            /// <summary>
            /// A specialized token for a <see cref="ItemFix.User.UserToken"/>
            /// </summary>
            UserToken, 
            /// <summary>
            /// This represents nothing
            /// </summary>
            None
        }

        /// <summary>
        /// No ID and <see cref="Type.None"/>
        /// </summary>
        public static ItemID None => new ItemID("", Type.None);

        /// <summary>
        /// The ID
        /// </summary>
        public string ID { get; }

        /// <summary>
        /// The type of ID this represents
        /// </summary>
        public Type IDType { get; }
    }
}
